### ISSUE TITLE
根據範例沒有產生 Client 

### ISSUE THREAD

**Issue by mikunalpha** [rpcxio/protoc-gen-gogorpcx#1]
嘗試先用指令安裝
`go get github.com/rpcxio/protoc-gen-gogorpcx/protoc-gen-gogofast`
然後跑
`protoc --gofast_out=plugins=rpcx:. helloworld.proto`
只有產生 message 的程式碼

**Comment by mikunalpha** [comment]
把 https://github.com/rpcxio/protoc-gen-rpcx/blob/master/rpcx/rpcx.go#L7 兩個 package 換成 gogo 的就重裝應該就正常了

**Comment by smallnest** [comment]
fixed. thanks
