### ISSUE TITLE
这个插件安装不上？

### ISSUE THREAD

**Issue by lwmonster** [rpcxio/protoc-gen-gogorpcx#12]
执行了以下安装命令，还是报错
`$ go get github.com/rpcxio/protoc-gen-gogorpcx/protoc-gen-gofast

go: downloading github.com/rpcxio/protoc-gen-gogorpcx v0.2.1
go: added github.com/rpcxio/protoc-gen-gogorpcx v0.2.1`

错误：
`$ protoc --gofast_out=plugins=rpcx:. hello.proto

protoc-gen-gofast: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--gofast_out: protoc-gen-gofast: Plugin failed with status code 1.
`

我看了PATH里确实没有 protoc-gen-gofast 这个可执行文件，GOPATH下是有github.com/rpcxio/protoc-gen-gogorpcx 的代码的，只是没有可执行的文件

**Comment by lwmonster** [comment]
@smallnest  这个安装有啥问题吗？ 难道需要自己编译成可执行文件么

**Comment by smallnest** [comment]
现在的go使用go install命令按照可执行文件，而不是go get

**Comment by smallnest** [comment]
protoc的插件都是可执行文件，需要安装

**Comment by lwmonster** [comment]
试了go install 也不行，自己build 一个，然后放到可执行目录里倒是可以了 :D

> 现在的go使用go install命令按照可执行文件，而不是go get
