### ISSUE TITLE
Unresolved reference 'MarshalToSizedBuffer'

### ISSUE THREAD

**Issue by LHRchina** [rpcxio/protoc-gen-gogorpcx#3]
There is an err when use   
> protoc --gofast_out=plugins=rpcx:.  ...

MarshalToSizedBuffer undefined (type *anypb.Any has no field or method MarshalToSizedBuffer)

**Comment by smallnest** [comment]
It is caused by this plugin?

You use official protobuf and *anypb.Any , and then use gogoproto?

**Comment by smallnest** [comment]
no more provided info. closed
