### ISSUE TITLE
生成的 pb.go 并没有 NewXClientForGreeter函数

### ISSUE THREAD

**Issue by CyJaySong** [rpcxio/protoc-gen-gogorpcx#5]
安装 readme 的例子。生成的 pb.go 并没有 NewXClientForGreeter函数

**Comment by CyJaySong** [comment]
看错了。。抱歉

**Comment by CyJaySong** [comment]
使用 gogofaster_out 时没有，gofast_out的时候，有

**Comment by smallnest** [comment]
是否安装了protoc-gen-gofaster插件? `go get github.com/rpcxio/protoc-gen-gogorpcx/protoc-gen-gofaster`

**Comment by CyJaySong** [comment]
安装了的

**Comment by CyJaySong** [comment]
我之前直接安装了protoc-gen-gogofaster插件， 刚刚安了一下protoc-gen-gogofast。然后再用gogofaster_out生成，便有了
